balotaje_mesas:
    resource: "@BalotajeBundle/Resources/config/routing/mesa.yml"
    prefix:   /mesas

resultados:
    path:     /resultados
    defaults: { _controller: "BalotajeBundle:Default:index" }