<?php

namespace BalotajeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MesaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesaRepository extends EntityRepository
{
    public function contarVotos($filtros = null) {

        $qb = $this->createQueryBuilder('m')
            ->select('SUM(m.resultadoCambiemos) as cambiemos, SUM(m.resultadoFpv) as fpv ');

        if ($filtros){
            if (($filtros['localidad'])){
                $qb->andWhere("m.localidad = :localidad")
                    ->setParameter("localidad", $filtros['localidad']);
            }
        }

        return $qb->getQuery()->getResult();
    }
}
