parameters:
#    util.example.class: UtilBundle\Example

services:
#    util.example:
#        class: %util.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    form.type.jqueryautocomplete:
        class: UtilBundle\Form\Type\JqueryAutocompleteType
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: jqueryautocomplete }
            
    form.type.bootstrapcollection:
        class: UtilBundle\Form\Type\BootstrapCollectionType
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: bootstrapcollection }

            
    form.type.jqueryautocompletetext:
        class: UtilBundle\Form\Type\JqueryAutocompleteTextType
        tags:
            - { name: form.type, alias: jqueryautocompletetext }
            
#    excel.tool:
#            class: UtilBundle\Services\ExcelTool
#            arguments:
#                phpexcel: "@phpexcel"
#                entityManager: "@doctrine.orm.entity_manager"
#            tags:
#                - { name: excel.tool, alias: excel.tool }

    form.type.verticalcollection:
        class: UtilBundle\Form\Type\VerticalCollectionType
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: verticalcollection }

#    genemu.form.jquery.type.select2:
#        class: UtilBundle\Form\Type\Select2Type
#        arguments:
#            entityManager: "@doctrine.orm.entity_manager"
#            abstract: true
#        tags:
#            - { name: form.type, alias: jquery.type.select2 }

