provincia:
    path:     /
    defaults: { _controller: "UbicacionBundle:Provincia:index" }

provincia_show:
    path:     /{id}/show
    defaults: { _controller: "UbicacionBundle:Provincia:show" }

provincia_new:
    path:     /new
    defaults: { _controller: "UbicacionBundle:Provincia:new" }

provincia_create:
    path:     /create
    defaults: { _controller: "UbicacionBundle:Provincia:create" }
    methods: POST

provincia_edit:
    path:     /{id}/edit
    defaults: { _controller: "UbicacionBundle:Provincia:edit" }

provincia_update:
    path:     /{id}/update
    defaults: { _controller: "UbicacionBundle:Provincia:update" }
    methods: [POST, PUT]

provincia_delete:
    path:     /{id}/delete
    defaults: { _controller: "UbicacionBundle:Provincia:delete" }
    methods: [POST, DELETE]
