ubicacion_homepage:
    path:     /hello/{name}
    defaults: { _controller: UbicacionBundle:Default:index }

UbicacionBundle_pais:
        resource: "@UbicacionBundle/Resources/config/routing/pais.yml"
        prefix:   /pais
        
UbicacionBundle_provincia:
        resource: "@UbicacionBundle/Resources/config/routing/provincia.yml"
        prefix:   /provincia
        
UbicacionBundle_departamento:
        resource: "@UbicacionBundle/Resources/config/routing/departamento.yml"
        prefix:   /departamento


UbicacionBundle_localidad:
        resource: "@UbicacionBundle/Resources/config/routing/localidad.yml"
        prefix:   /localidad
