parameters:
#    ubicacion.example.class: UbicacionBundle\Example

services:
#    ubicacion.example:
#        class: %ubicacion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
